[package]
name = "robots"
version = "0.1.0"
authors = ["Dimitri Merejkowsky <d.merej@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
